### PR TITLE
[BUGFIX] Detect Authenticator enabled state in User Settings

### LINKED ISSUE #155: Authenticator enabled not detected in User Settings (has fix)
# Bug report

I'm creating a pull request with a fix for this shortly.

## Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description:

When going to User settings, the secret and QR will always be displayed.

## Steps to reproduce:

1. Go to User settings --> Google Authenticator
2. Enable Google Authenticator and go through the necessary steps.
3. After saving, the QR code and secret field will still be displayed.

## Expected results:

The user should be shown a field where a one-time code can be entered to disable Google Authenticator again.

## Environment

TYPO3 9.5.19, PHP 7.2

### PR DESCRIPTION
**Pull request by mabolek**
Fixes #155

### CODE REVIEW

File: Classes/Hook/UserSettings.php [hunk 1]
```diff
@@ -205,6 +205,9 @@ private function getSecretKey(): string
 
     private function isGoogleAuthenticatorEnabled(): bool
     {
+        if ($this->data['type'] === 'user' && !is_array($this->data['row'])) {
+            $this->data['row'] = $GLOBALS['BE_USER']->user;
```
Comment (codeFareith) [inline Classes/Hook/UserSettings.php:209]: Codacy found an issue: [Direct use of $GLOBALS Superglobal detected.](https://app.codacy.com/manual/robinvonberg/cf_google_authenticator/pullRequest?prid=5757557)

**Comment by codeFareith** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/robinvonberg/cf_google_authenticator/pullRequest?prid=5757557&bid=18846997)

File: Classes/Hook/UserSettings.php (hunk 1 above)
Comment (mabolek) [reply Classes/Hook/UserSettings.php:209]: IMO there's not really any better way. https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/BackendUserObject/Index.html
